[tool.poetry]
name = "tb-pe-client"
version = "4.3.1.4"
description = "Python REST client for ThingsBoard Professional Edition"
authors = ["ThingsBoard Authors <info@thingsboard.io>"]
license = "Apache-2.0"
homepage = "https://github.com/thingsboard/thingsboard-python-client"
repository = "https://github.com/thingsboard/thingsboard-python-client"
keywords = ["thingsboard", "iot", "rest", "client"]
classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: Apache Software License",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Topic :: Software Development :: Libraries :: Python Modules",
]
packages = [
    { include = "tb_pe_client" }
]

[tool.poetry.dependencies]
python = ">=3.10,<4.0"
pydantic = ">=2.0,<3.0"
urllib3 = ">=1.26,<3.0"
python-dateutil = ">=2.8.2,<3.0"
typing-extensions = ">=4.6.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
